//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "craft_recipe")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: u32,
	pub craft_id: u32,
	pub index: Option<u32>,
	pub r#type: Option<String>,
	pub name: Option<String>,
	pub specification: Option<String>,
	#[sea_orm(column_type = "Float", nullable)]
	pub rate: Option<f32>,
	pub memo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
