//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "film_property")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub r#type: String,
	pub category_one: String,
	pub category_two: String,
	pub corona: String,
	#[sea_orm(column_type = "Float")]
	pub density: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
