//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "film_type")]
pub struct Model {
	pub r#type: String,
	pub category: String,
	pub sub_category: String,
	pub thickness: i32,
	#[sea_orm(column_type = "Float")]
	pub output: f32,
	pub line: i32,
	#[sea_orm(primary_key)]
	pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
