//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

pub mod prelude;

pub mod accessory_column;
pub mod craft;
pub mod craft2schedule;
pub mod craft_recipe;
pub mod dispatcher;
pub mod event;
pub mod film_property;
pub mod film_type;
pub mod film_type_order;
pub mod lab_tds;
pub mod order;
pub mod order_accessory;
pub mod order_detail;
pub mod permission;
pub mod recipe_lib;
pub mod recipe_lib_detail;
pub mod recipe_name;
pub mod role;
pub mod schedule;
pub mod schedule2scheme;
pub mod scheme;
pub mod scheme2order;
pub mod scheme_detail;
pub mod scheme_order;
pub mod scheme_slice;
pub mod sub_module;
pub mod sub_system;
pub mod thickness_length;
pub mod user;
