//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "order_accessory")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: u32,
	pub order_id: Option<i32>,
	pub category: Option<String>,
	pub accessory: Option<String>,
	pub count: Option<u32>,
	pub situation: Option<String>,
	pub state: Option<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
