//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "scheme")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub datetime: DateTime,
	pub user: u32,
	pub line: i32,
	pub width: i32,
	pub memo: Option<String>,
	pub state: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
