//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scheme_order")]
pub struct Model {
	pub scheme_id: u32,
	pub order_detail: u32,
	pub width: u32,
	pub roll: u32,
	pub length: u32,
	#[sea_orm(primary_key)]
	pub id: i32,
	pub r#type: String,
	#[sea_orm(column_type = "Float")]
	pub thickness: f32,
	pub scheme_rolls: i32,
	pub state: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
