//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scheme_detail")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub scheme_id: i32,
	pub r#type: String,
	pub thickness: i32,
	pub length: i32,
	pub roll: i32,
	#[sea_orm(column_type = "Float")]
	pub weight: f32,
	pub arrange: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
